nitfc-festival-system-team/2023hp

- src/components/Map.tsx
- src/components/Notice.tsx
- src/components/Schedule.tsx
- src/components/Stand.tsx
- src/components/Title.tsx
- src/pages/contents/map.tsx
- src/pages/contents/notice.tsx
- src/pages/contents/schedule.tsx
- src/pages/contents/stand.tsx
- src/pages/index.tsx
Closes #4 
- トップページのレイアウトとコンポーネントを作った
- トップページのレイアウト検討
- コンポーネントの中作る
> feat: 基礎コンポーネントを作成

- package-lock.json
- package.json
- src/components/fadeAnimation.tsx
- src/components/fadeAnimationProvider.tsx
- src/pages/index.tsx
-フェードアニメーションを追加
- <FadeAnimation></FadeAnimation>で囲むことで画面内に出現時に囲んだ要素がフェードインする
-
> feat: フェードアニメーションを追加

- src/pages/_document.tsx
> 12-リロードしたらスクロールを促す表示のStyleが消える

- src/components/PageTransitionButton.tsx
- src/pages/index.tsx
> feat: 遷移ボタン実装

- src/db/notice.ts
- src/db/schedule.ts
- src/db/stand.ts
- src/types/notice.ts
- src/types/schedule.ts
- src/types/stand.ts
Closes #28 
-DBのスキーマ？とテストデータを定義
-
> 28 dbの雛形を作る

- src/components/NoticeList.tsx
- src/components/NoticeScrollableComponent.tsx
- src/db/notice.ts
- src/db/schedule.ts
- src/db/stand.ts
Closes #27 
-dbのファイルからデータを撮ってきてリスト表示するようにした
-
> 27 お知らせをリスト構造にする

- src/styles/globals.css
Closes #<issue No.36>
-globals.cssにダークモードの時、背景を...にするみたいな処理があったので、全部削除しました。
削除した後、ターミナルでnpm run buildとnpm run fmtとnpm run lintを実行しました。
メインページ、お知らせページ、企画ページ、露店ページを確認しましたが、ライトモードとダークモードで違いは見られませんでした。
-特になし、ダークモードは消え去りました。
> ダークモードに関する処理を削除

- src/components/Title.tsx
> fix: タイトルを中央ぞろえにする

- .eslintrc.json
- README.md
- package-lock.json
- package.json
- src/components/Map.tsx
- src/db/notice.ts
- src/pages/index.tsx
> npm-run-fmtが動くようにする

- src/components/Notice.tsx
- src/components/NoticeList.tsx
- src/components/NoticeScrollableComponent.tsx
- src/db/notice.ts
- src/pages/index.tsx
Closes #35 
- レスポンシブデザインにもしたよ
-
> 35 お知らせをクリックすると関連ページに飛ぶようにする

- src/components/Map.tsx
> style: 画像サイズをRDに

- package-lock.json
- package.json
- src/components/PageTransitionButton.tsx
Closes #54 
- ライブラリ入れた
- ボタンにアニメーションつけた
-
> 54 framer motionを試す

- src/components/PageTransitionButton.tsx
- src/pages/_app.tsx
> 43 画面遷移にエフェクトをつける

- src/components/EventOverlay.tsx
- src/db/schedule.ts
- dbからイベントを参照し、開催中、すぐに開催中予定のものを条件付きで表示
- デバッグは気合でやって
-
> 44 開催中イベント表示をdbから参照する様にする

- src/components/Notice.tsx
- src/components/NoticeList.tsx
- src/components/NoticeScrollableComponent.tsx
> feat: リンクボタン追加

- src/components/PageTransitionButton.tsx
> 75 企画と露店のボタンの文字以外を押すとアニメーションだけ動いてリンクに飛ばない

- src/components/Schedule.tsx
> 企画ページで日付を固定する

- src/components/Schedule.tsx
- src/db/schedule.ts
- src/types/schedule.ts
> 企画ページで同じ場所をまとめる

- src/components/NoticeList.tsx
- src/components/Schedule.tsx
- src/lib/prisma.js
> 110 dbをローカルに戻す

- src/db/schedule.ts
Closes #<issue No.117>
-Day1～Day3のスケジュールをデータベースにぶちこんだ。
-花火の仮データの変更、npm run build、npm run fmt、npm run lintの実行
> 117 パンフレットのスケジュールをデータベースにぶちこみます

- src/components/Schedule.tsx
> 拡大率調整と高さ調整

- src/components/Footer.tsx
- src/components/LinkedText.tsx
> feat: PC/スマホでフッターを分けた

- src/components/Schedule.tsx
> 122 イベントを押したら情報が下に出るようにする

- src/components/Notice.tsx
- src/components/NoticeList.tsx
- src/components/PageTransitionButton.tsx
- src/components/VerticalLine.tsx
- src/components/scrollStyle.tsx
> 128 pcスマホで要素の大きさを変える

- src/components/EventOverlay.tsx
> feat: イベント表示が改行されないようにした

- src/components/Footer.tsx
- src/components/StandList.tsx
> feat: 露店番号を表示

- .github/workflows/ci.yaml
- src/components/EventOverlay.tsx
- src/components/Footer.tsx
- src/components/Notice.tsx
- src/components/OpenDate.tsx
- src/components/PageTransitionButton.tsx
- src/components/scrollStyle.tsx
- src/styles/globals.css
> 135 全体的に統一感を出す

- src/components/Footer.tsx
- src/pages/contents/stand.tsx
> feat: フッター追加

- src/components/Title.tsx
> 154 タイトルが右にズレるのを修正

- src/components/VenueImageMap.tsx
> 159-露店位置変更に伴う諸変更

- src/components/Schedule.tsx
- src/components/ScheduleMoveButton.tsx
> style: ボタンのスタイル変更

- src/components/Schedule.tsx
> 150 現在時刻マーカーを追加

- src/components/Schedule.tsx
- 日付のフォーマットを変更
- 不要な時間帯を削ぐのは不可能！駄ライブラリ！
-
> 164 スケジュールの不要な時間を削ぐ日付表示を変更

- src/components/LinkedText.tsx
> fix: 絶対パスでリダイレクトするよう修正

- src/components/Schedule.tsx
> 175 スケジュールのスクロール感度調整

- src/components/Schedule.tsx
> 188 スケジュール表示範囲を高専祭開始時からにする

- src/components/EventOverlay.tsx
- EventOverlay.tsxにoffsetを追加条件式編集
-
> イベントが開催中にちゃんとなる
